{:namespaces
 ({:doc
   "\nThe API below was written regarding to the source code\nof different Webdriver implementations. All of them partially differ\nfrom the official W3C specification.\n\nChrome:\nhttps://github.com/bayandin/chromedriver/blob/master/client/command_executor.py\nhttps://github.com/bayandin/chromedriver/blob/master/client/webelement.py\n\nFirefox (Geckodriver):\nhttps://github.com/mozilla/webdriver-rust/blob/master/src/httpapi.rs\n\nPhantom.js (Ghostdriver)\nhttps://github.com/detro/ghostdriver/blob/master/src/request_handlers/session_request_handler.js\nhttps://github.com/detro/ghostdriver/blob/master/src/request_handlers/webelement_request_handler.js\n",
   :name "etaoin.api",
   :wiki-url "etaoin.api-api.html",
   :source-url nil}
  {:doc nil,
   :name "etaoin.client",
   :wiki-url "etaoin.client-api.html",
   :source-url nil}
  {:doc "https://www.w3.org/TR/webdriver/#keyboard-actions",
   :name "etaoin.keys",
   :wiki-url "etaoin.keys-api.html",
   :source-url nil}
  {:doc nil,
   :name "etaoin.proc",
   :wiki-url "etaoin.proc-api.html",
   :source-url nil}),
 :vars
 ({:raw-source-url nil,
   :name "back",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 270,
   :var-type "function",
   :arglists ([driver]),
   :doc "Move backwards in a browser's history.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/back"}
  {:raw-source-url nil,
   :name "defmethods",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 43,
   :var-type "macro",
   :arglists ([multifn dispatch-vals & fn-tail]),
   :doc "Declares multimethods in batch.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/defmethods"}
  {:raw-source-url nil,
   :name "forward",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 284,
   :var-type "function",
   :arglists ([driver]),
   :doc "Move forwards in a browser's history.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/forward"}
  {:raw-source-url nil,
   :name "get-element-size",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 529,
   :var-type "function",
   :arglists ([driver q]),
   :doc
   "Returns an element size as a map with :width and :height keys.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/get-element-size"}
  {:raw-source-url nil,
   :name "get-title",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 303,
   :var-type "function",
   :arglists ([driver]),
   :doc "Returns the current window's title.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/get-title"}
  {:raw-source-url nil,
   :name "get-url",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 295,
   :var-type "function",
   :arglists ([driver]),
   :doc "Returns the current URL string.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/get-url"}
  {:raw-source-url nil,
   :name "q-expand",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 335,
   :var-type "function",
   :arglists ([driver q]),
   :doc
   "Expands a query expression into a pair of\n[locator, term] values to pass them into low-level HTTP API.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/q-expand"}
  {:raw-source-url nil,
   :name "q-xpath",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 315,
   :var-type "function",
   :arglists ([q]),
   :doc
   "Turns a map into an XPath clause.\n\n{:tag :div :id :content :class :test :index 2}\n//div[@id='content'][@class='test'][2]",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/q-xpath"}
  {:raw-source-url nil,
   :name "query",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 396,
   :var-type "function",
   :arglists ([driver q]),
   :doc
   "Finds an element on a page.\n\nA query might be:\n\n- a string, so the current browser's locator will be used. Examples:\n//div[@id='content'] for XPath,\ndiv.article for CSS selector\n\n- a keyword :active that means the current active element\n\n- a map with either :xpath or :css keys with a string term, e.g:\n{:xpath \"//div[@id='content']\"} or\n{:css \"div.article\"}\n\n- a map that will turn into an XPath expression:\n{:tag :div} => .//div\n{:id :container} => .//*[@id='container']\n{:tag :a :class :external :index 2} => .//a[@class='external'][2]\n\n- a vector of any clause mentioned above. In that case,\nevery next term is searched inside the previous one. Example:\n[{:id :footer} {:tag :a}] => finds the first hyperlink\ninside a div with id 'footer'.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/query"}
  {:raw-source-url nil,
   :name "random-port",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 49,
   :var-type "function",
   :arglists ([]),
   :doc "Returns a random port skiping first 1024 ones.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/random-port"}
  {:raw-source-url nil,
   :name "refresh",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 277,
   :var-type "function",
   :arglists ([driver]),
   :doc "Reload the current window.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/refresh"}
  {:raw-source-url nil,
   :name "wait",
   :file "src/etaoin/api.clj",
   :source-url nil,
   :line 975,
   :var-type "function",
   :arglists ([driver sec] [sec]),
   :doc "Does nothing for N seconds.",
   :namespace "etaoin.api",
   :wiki-url "/etaoin.api-api.html#etaoin.api/wait"})}
